/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmEditarUsuario.java
 *
 * Created on 07-dic-2013, 12:34:46
 */
package formularios;

import bd.Conexion;
import entidades.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author and1_p
 */
public class FrmEditarUsuario extends javax.swing.JFrame {
FrmMantenimientoUsuario Fmr;
    /** Creates new form FrmEditarUsuario */
    public FrmEditarUsuario(String id_usuario, FrmMantenimientoUsuario Fmr) {
        this.Fmr= Fmr;
        initComponents();
        setLocationRelativeTo(null);
        txt_clave.setEnabled(false);
        
         Conexion c = new Conexion();
        try{
            c.conectar();
            Usuario u = (Usuario)c.consultarUsuario(id_usuario,"id_usuario").get(0);
            this.txt_usuario.setText(u.getId_usuario());       
            this.txt_fecha.setText(String.valueOf(u.getFecha_Creacion()));
            this.cd_estado.setSelectedItem(u.getEstado()); 
            this.cb_rol.setSelectedItem(u.getRol());
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR AL CONSULTAR LOS DATOS DEL USUARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
     public FrmEditarUsuario() {
     initComponents();
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_clave = new javax.swing.JPasswordField();
        Chbox = new javax.swing.JCheckBox();
        cd_estado = new javax.swing.JComboBox();
        cb_rol = new javax.swing.JComboBox();
        txt_fecha = new javax.swing.JTextField();
        BtnEditar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID USUARIO:");

        jLabel2.setText("CLAVE:");

        jLabel3.setText("ESTADO:");

        jLabel4.setText("ROL:");

        jLabel5.setText("FECHA DE CREACION:");

        txt_usuario.setEditable(false);

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });

        Chbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChboxMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChboxMouseClicked(evt);
            }
        });
        Chbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChboxActionPerformed(evt);
            }
        });

        cd_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "A" }));

        cb_rol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "A" }));

        txt_fecha.setEnabled(false);

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.jpg"))); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(26, 26, 26)
                                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cd_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Chbox)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpiar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cd_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Chbox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEditar)
                    .addComponent(BtnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_claveActionPerformed

private void ChboxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChboxMouseReleased

        txt_clave.setEnabled(false);
}//GEN-LAST:event_ChboxMouseReleased

private void ChboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChboxMouseClicked

        if(Chbox.isSelected()){
            txt_clave.setEnabled(true);
        }
}//GEN-LAST:event_ChboxMouseClicked

private void ChboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChboxActionPerformed

}//GEN-LAST:event_ChboxActionPerformed

private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
this.getContentPane().setBackground(Color.CYAN);       
        if(this.txt_clave.isEnabled()){
        
        if(registroValido1()){
            
            
    String id_usuario = this.txt_usuario.getText();
    String clave = String.valueOf(this.txt_clave.getPassword());
    char estado = this.cd_estado.getSelectedItem().toString().charAt(0);
    char rol =  this.cb_rol.getSelectedItem().toString().charAt(0);
    
    
    
        Conexion c = new Conexion();

        try{
            c.conectar();
                 Usuario u = new Usuario(id_usuario, clave, rol,estado,null);
          
            if (c.modificarUsuario2(u)){
          
               
            JOptionPane.showMessageDialog(null, "SE MODIFICO CORRECTAMENTE EL REGISTRO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            this.Fmr.consultar_usuario();
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA EDICION", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

                     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA CONEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
      }
     }else {
            
       if(registroValido2()){
            
            
    String id_usuario = this.txt_usuario.getText();
    String clave = String.valueOf(this.txt_clave.getPassword());
    char estado = this.cd_estado.getSelectedItem().toString().charAt(0);
    char rol =  this.cb_rol.getSelectedItem().toString().charAt(0);
    
    
        Conexion c = new Conexion();

        try{
            c.conectar();
            Usuario u = new Usuario(id_usuario, clave,estado,rol,null);
          
            if (c.modificarUsuario1(u)){
          
               
            JOptionPane.showMessageDialog(null, "SE MODIFICO CORRECTAMENTE EL REGISTRO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            this.Fmr.consultar_usuario();
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA EDICION", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

                     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA CONEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
      }
     }                
            
}//GEN-LAST:event_BtnEditarActionPerformed
private boolean registroValido1(){

     if(this.txt_usuario.getText().trim().equals("") ||
       this.txt_clave.getText().equals("") 
      
      
       ){
        JOptionPane.showMessageDialog(null, "FALTA CAMPOS DE LLENAR EN EL REGISTRO", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
    }
     
     String clave = this.txt_clave.getText();     
     try{                  
        if(!(clave.length() >= 6)){
            JOptionPane.showMessageDialog(null, "LA CONTRASEÑA DEBE CONTENER AL MENOS 6 DIGITOS ", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
        }                
     }catch(Exception e){  
     }
  
return true;
}

private boolean registroValido2(){

     if(this.txt_usuario.getText().trim().equals("")
         
       ){
        JOptionPane.showMessageDialog(null, "FALTA CAMPOS DE LLENAR EN EL REGISTRO", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
    }
  
return true;
}

    private void limpiarRegistro(){
    
    this.txt_usuario.setText(null);
    this.txt_clave.setText(null);
   }
    
private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
         limpiarRegistro();
}//GEN-LAST:event_BtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JCheckBox Chbox;
    private javax.swing.JComboBox cb_rol;
    private javax.swing.JComboBox cd_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
