/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmVenta.java
 *
 * Created on 26/11/2012, 09:39:38 AM
 */
package formularios;

import bd.Conexion;
import entidades.Cliente;
import entidades.Detalle_Factura;
import entidades.Factura;
import entidades.Telefono;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VR
 */
public class FrmFactura extends javax.swing.JFrame {
    
    
    FrmBuscarCliente frm;
    ArrayList telefonos;
 
float auy_num =0;
double iva =0;
double total = 0;
Detalle_Factura df = new Detalle_Factura();  
ArrayList<Detalle_Factura> tabla_listado = new ArrayList<Detalle_Factura>();
    
//    private  String numero_factura="";

    /** Creates new form FrmVenta */
    public FrmFactura(String identificacion,FrmBuscarCliente frm) {
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.frm =frm;
        telefonos = new ArrayList();
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTelefonos();
        
        Conexion c = new Conexion();
       
        try{
            c.conectar();
            Cliente cl = (Cliente)c.consultarCliente(identificacion,"identificacion").get(0);
            this.txt_idcliente.setText(cl.getId_cliente());
            this.txt_id_cliente.setText(cl.getIdentificacion());
            this.txt_nombre.setText(cl.getNombre());
            this.txt_direccion.setText(cl.getDireccion());           
            this.txt_telefono.setText(cl.getTelefono());
          
            
        }catch(Exception e){
        }

    }
    
  public void cargarTelefonos(){
      
      
        Conexion c = new Conexion();
        try{
            c.conectar();
            ArrayList resultado = c.consultarTelefonos();
            this.telefonos = resultado;
            String[] telefonos = new String[resultado.size()];
            for(int i=0; i<resultado.size(); i++){
                
                Telefono t = (Telefono)resultado.get(i);
                int id_telefono     = t.getId_telefono();
                String marca       = t.getMarca();
                String modelo       = t.getModelo();
                String descripcion  = t.getDescripcion(); 
                float precio        = t.getPrecio();    
                telefonos[i]        =id_telefono+" | " +marca+" "+modelo+" "+descripcion+" | $"+precio;
                this.cb_producto.addItem(telefonos[i]);
            }            
            cb_producto.setModel(new javax.swing.DefaultComboBoxModel(telefonos));                        
        }catch(Exception e){
        
        }
    } 
      
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        cb_producto = new javax.swing.JComboBox();
        txt_cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BT_agregar = new javax.swing.JButton();
        BT_quitar = new javax.swing.JButton();
        BT_ingresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_id_cliente = new javax.swing.JTextField();
        txt_idcliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txt_nombre.setEditable(false);

        txt_direccion.setEditable(false);

        txt_telefono.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Cliente:");

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Dirección:");

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Teléfono:");

        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("CI/RUC:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        jButton1.setText("CONSULTAR CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Id telefono", "Descripción", "Precio Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(tb_productos);

        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Producto:");

        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Cantidad:");

        BT_agregar.setText("+");
        BT_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_agregarActionPerformed(evt);
            }
        });

        BT_quitar.setText("-");
        BT_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_quitarActionPerformed(evt);
            }
        });

        BT_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingreso.jpg"))); // NOI18N
        BT_ingresar.setText("Ingresar");
        BT_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ingresarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Subtotal");

        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("IVA");

        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Total");

        txt_subtotal.setEditable(false);

        txt_iva.setEditable(false);

        txt_total.setEditable(false);

        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Código:");

        txt_codigo.setFont(new java.awt.Font("Tahoma", 1, 14));
        txt_codigo.setText("Fact#001-001-0000112");
        txt_codigo.setSelectionColor(new java.awt.Color(51, 51, 255));

        txt_id_cliente.setEditable(false);

        txt_idcliente.setEditable(false);

        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(371, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(BT_agregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BT_quitar))
                                    .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_id_cliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_direccion))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(BT_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txt_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(BT_agregar)
                    .addComponent(BT_quitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BT_ingresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BT_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ingresarActionPerformed
// TODO add your handling code here:           
    
    
    String codigo    = this.txt_codigo.getText();
    int id_cliente  = Integer.parseInt(this.txt_idcliente.getText());   
    
    float Subtotal = Float.parseFloat(this.txt_subtotal.getText());
    float iva = Float.parseFloat(this.txt_iva.getText());
    float total = Float.parseFloat(this.txt_total.getText());
    int cantidad = Integer.parseInt(this.txt_cantidad.getText());

    
    
    Conexion c = new Conexion();
    
    try{        
       
        c.conectar();
        
        Factura f = new Factura();
        f.setCodigo(codigo);
        f.setId_cliente(id_cliente);
        f.setSubtotal(Subtotal);
        f.setIva(iva);
        f.setTotal(total);     
        if(c.procesarVenta(f,tabla_listado)){
        JOptionPane.showMessageDialog(rootPane,"SE REALIZO LA VENTA CON ÉXITO", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
         FrmFactura frm = new FrmFactura (null,null);
         frm.setVisible(true);
         this.dispose();
         
        }else{
            JOptionPane.showMessageDialog(rootPane,"DEBE INGRESAR OTRO NUMERO DE FACTURA", "ERROR", JOptionPane.INFORMATION_MESSAGE);                    
        }
        
    }catch(Exception e){
    JOptionPane.showMessageDialog(rootPane,"OCURRIÓ UN ERROR EN LA CONEXIÓN", "ERROR", JOptionPane.ERROR_MESSAGE);                    
    }     
    c.desconectar();
      
}//GEN-LAST:event_BT_ingresarActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   FrmBuscarCliente frm = new FrmBuscarCliente ();
    frm.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed



private void BT_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_agregarActionPerformed
   
    
      try{
        int id_telefono = Integer.parseInt(((String)this.cb_producto.getSelectedItem()).split("\\|")[0].trim());    
        Telefono  t      = Telefono.obtenerProductoPorId(this.telefonos, id_telefono);
        int cantidad    = Integer.parseInt(this.txt_cantidad.getText());        
        DefaultTableModel tb = (DefaultTableModel)tb_productos.getModel();
        
        int fila =tb.getRowCount();
        tb.insertRow(fila,new Object[]{cantidad,t.getId_telefono(),t.getMarca(),t.getPrecio(),t.getPrecio()*cantidad}); 
        
        float l = t.getPrecio()*cantidad;
        auy_num+=l;
        txt_subtotal.setText(String.valueOf(auy_num));
        iva = Math.rint((auy_num * 0.12)*100)/100;
        txt_iva.setText(String.valueOf(iva));
        total = Math.rint((auy_num + iva)*100)/100;
        txt_total.setText(String.valueOf(total));
        
        
        Detalle_Factura detalle = new Detalle_Factura();    
      
        detalle.setId_telefono(id_telefono);        
        detalle.setCantidad(cantidad);
        detalle.setPrecio(t.getPrecio());
        detalle.setTotal(l); 
        
        tabla_listado.add(detalle);
        
        
    }catch(Exception e){
        System.out.println(e.toString());
        JOptionPane.showMessageDialog(rootPane,"DEBE INGRESAR UNA CANTIDAD", "", JOptionPane.INFORMATION_MESSAGE);                    
    }    
    
    
}//GEN-LAST:event_BT_agregarActionPerformed

private void BT_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_quitarActionPerformed
// TODO add your handling code here:
    int  indices = this.tb_productos.getSelectedRow();
         tabla_listado.remove(indices) ;  
         DefaultTableModel elimina = (DefaultTableModel) tb_productos.getModel();
        elimina.removeRow(indices);   
}//GEN-LAST:event_BT_quitarActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_agregar;
    private javax.swing.JButton BT_ingresar;
    private javax.swing.JButton BT_quitar;
    private javax.swing.JComboBox cb_producto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_productos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_idcliente;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
