/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmIngresarTelefono.java
 *
 * Created on 31/10/2013, 04:35:35 PM
 */
package formularios;
import bd.Conexion;
import entidades.Telefono;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author VR
 */
public class FrmIngresarTelefono extends javax.swing.JFrame {
FrmMantenimientoTelefono Fmr;

    /** Creates new form FrmIngresarTelefono */
    public FrmIngresarTelefono(FrmMantenimientoTelefono Fmr) {
        this.Fmr =Fmr;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public FrmIngresarTelefono() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc_imagen = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        BtnIngreso = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb_marca = new javax.swing.JComboBox();
        cb_modelo = new javax.swing.JComboBox();
        txt_imagen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO INGRESO TELEFONO");

        jLabel1.setText("CODIGO:");

        jLabel2.setText("MARCA:");

        jLabel3.setText("MODELO:");

        jLabel4.setText("DESCRIPCION:");

        jLabel5.setText("PRECIO:");

        BtnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar.png"))); // NOI18N
        BtnIngreso.setText("INGRESAR");
        BtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.jpg"))); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAMSUNG", "MOTOROLA", "NOKIA", "BLAKBERRY" }));

        cb_modelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GALAXY GRAND 2S", "GALAXY S4 ZOOM", "GALAXY WIN DUOS ", "GALAXY POCKET NEO", "MOTO G", "MOTOGO TV", "MOTOSMARTPLUS", "ATRIX 2", "LUMIA 1520", "ASHA 205", "ASHA 210", "ASHA 309" }));

        txt_imagen.setEditable(false);

        jLabel6.setText("IMAGEN:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        jButton1.setText("SELECCIONAR UBICACION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_marca, 0, 394, Short.MAX_VALUE)
                                .addComponent(cb_modelo, javax.swing.GroupLayout.Alignment.LEADING, 0, 394, Short.MAX_VALUE)
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(104, 104, 104))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(BtnIngreso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String obtenerRutaImagen(){
    String ruta = "";
    int returnVal = fc_imagen.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc_imagen.getSelectedFile();
        try {
            ruta = file.getAbsolutePath();
        } catch (Exception ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    }
    return ruta;
} 
  
    
   private boolean registroValido(){

     if(this.txt_codigo.getText().trim().equals("") ||
       this.txt_descripcion.getText().trim().equals("") ||
       this.txt_precio.getText().trim().equals("")
        )
     
     {
        JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS CAMPOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
    }
     
       try{
      Float.parseFloat(this.txt_precio.getText());
      
     }catch(Exception e){
      JOptionPane.showMessageDialog(null, "PRECIO INVALIDO, DEBE SER ENTERO O DECIMAL", "ERROR", JOptionPane.ERROR_MESSAGE);
       return false;
     }
       
            
     try{                
       Integer.parseInt(this.txt_codigo.getText());{
    
        }                
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "EL CODIGO DEBE SER ENTERO", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
     }
       
       
       
       
       return true;
       
       
       
} 
    
private void limpiarFormulario(){
    this.txt_codigo.setText("");
    this.txt_descripcion.setText("");
    this.txt_precio.setText("$");
   
   }    
    
    
    private void BtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresoActionPerformed
   this.getContentPane().setBackground(Color.DARK_GRAY);       
        
    if(registroValido()){
    int codigo =Integer.parseInt(this.txt_codigo.getText());
    String marca = this.cb_marca.getSelectedItem().toString();
    String modelo = this.cb_modelo.getSelectedItem().toString();
    String descripcion = this.txt_descripcion.getText();
    float precio = Float.parseFloat(this.txt_precio.getText());
    String ruta_imagen = this.txt_imagen.getText();
    
    Conexion c = new Conexion();
    try{
        c.conectar();
        Telefono t = new Telefono(codigo, marca, modelo, descripcion, precio,new File(ruta_imagen));
        if(c.ingresarTelefono(t)){
            JOptionPane.showMessageDialog(null, "SE INGRESO CORRECTAMENTE EL REGISTRO", "EXITO", JOptionPane.INFORMATION_MESSAGE);  
           this.Fmr.consultar_telefono();
           limpiarFormulario();
                    
        }
else{
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN EL INGRESO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }catch(Exception e){
  
    JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA CONEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    }   
    }//GEN-LAST:event_BtnIngresoActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    String ruta = this.obtenerRutaImagen();
    if(!ruta.equals("")){
        this.txt_imagen.setText(ruta);
    }
    
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngreso;
    private javax.swing.JComboBox cb_marca;
    private javax.swing.JComboBox cb_modelo;
    private javax.swing.JFileChooser fc_imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_imagen;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
