/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmIngresarUsuario.java
 *
 * Created on 07-dic-2013, 12:16:45
 */
package formularios;

import bd.Conexion;
import entidades.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author and1_p
 */
public class FrmIngresarUsuario extends javax.swing.JFrame {

    FrmMantenimientoUsuario Fmr;

    /** Creates new form FrmIngresarUsuario */
    public FrmIngresarUsuario(FrmMantenimientoUsuario Fmr) {
        this.Fmr = Fmr;
        setLocationRelativeTo(null);
        initComponents();
        
    }

    public FrmIngresarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_rol = new javax.swing.JComboBox();
        cb_estado = new javax.swing.JComboBox();
        BtnIngreso = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        txt_clave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("ID USUARIO:");

        jLabel2.setText("CLAVE:");

        jLabel3.setText("ROL:");

        jLabel4.setText("ESTADO:");

        cb_rol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "A" }));

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "A" }));

        BtnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar.png"))); // NOI18N
        BtnIngreso.setText("Ingresar");
        BtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresoActionPerformed(evt);
            }
        });

        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.jpg"))); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_clave)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnIngreso)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpiar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean registroValido() {

        if (this.txt_usuario.getText().trim().equals("")
                || this.txt_clave.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS CAMPOS", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        String clave = this.txt_clave.getText();
        try {
            if (!(clave.length() >= 5)) {
                JOptionPane.showMessageDialog(null, "LA CONTRASEÑA DEBE MAS DE 4 DIGITOS ", "ERROR", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (Exception e) {
        }
        Conexion c = new Conexion();
        String id = this.txt_usuario.getText();
        try {
            c.conectar();
            ArrayList usuario = c.consultarUsuarioporid();

            for (int i = 0; i < usuario.size(); i++) {
                Usuario u = (Usuario) c.consultarUsuarioporid().get(i);
                if (u.getId_usuario().equals(id)) {
                    JOptionPane.showMessageDialog(null, "EL USUARIO YA SE ENCUENTRA REGISTRADO, ELIJA OTRO ID", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        } catch (Exception e) {
        }
        return true;
    }

private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_usuarioActionPerformed

private void BtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresoActionPerformed
    this.getContentPane().setBackground(Color.DARK_GRAY);
    if (registroValido()) {

        String id_usuario = this.txt_usuario.getText();
        String clave = String.valueOf(this.txt_clave.getPassword());
        char estado = this.cb_estado.getSelectedItem().toString().charAt(0);
        char rol = this.cb_rol.getSelectedItem().toString().charAt(0);
       

        Conexion c = new Conexion();
        try {
            c.conectar();

            Usuario u = new Usuario(id_usuario, clave, estado, rol,null);

            if (c.ingresarUsuario(u)) {
                JOptionPane.showMessageDialog(null, "SE INGRESO CORRECTAMENTE EL REGISTRO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                this.Fmr.consultar_usuario();

            } else {
                JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN EL INGRESO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA CONEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }
}//GEN-LAST:event_BtnIngresoActionPerformed


private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
    limpiarFormulario();
}//GEN-LAST:event_BtnLimpiarActionPerformed

private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_claveActionPerformed
    private void limpiarFormulario() {
        this.txt_usuario.setText("");
        this.txt_clave.setText("");
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngreso;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JComboBox cb_estado;
    private javax.swing.JComboBox cb_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
