/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMantenimientoUsuario.java
 *
 * Created on 06-dic-2013, 23:48:46
 */
package formularios;
import bd.Conexion;
import entidades.Cliente;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author and1_p
 */
public class FrmMantenimientoCliente extends javax.swing.JFrame {

    /** Creates new form FrmMantenimientoUsuario */
    public FrmMantenimientoCliente() {

        initComponents();
        actualizar_descripcion();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Editar1 = new javax.swing.JButton();
        btn_Ingresar2 = new javax.swing.JButton();
        btn_eliminar1 = new javax.swing.JButton();
        cb_tipo = new javax.swing.JComboBox();
        btn_consultar = new javax.swing.JButton();
        txt_descripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_resultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_Editar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_Editar1.setText("Editar");
        btn_Editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Editar1ActionPerformed(evt);
            }
        });

        btn_Ingresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingreso.jpg"))); // NOI18N
        btn_Ingresar2.setText("Ingresar");
        btn_Ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar2ActionPerformed(evt);
            }
        });

        btn_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar1.setText("Eliminar");
        btn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar1ActionPerformed(evt);
            }
        });

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "IDENTIFICACION", "NOMBRE", "DIRECCION" }));
        cb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoActionPerformed(evt);
            }
        });

        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        Tb_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICACION", "NOMBRE", "DIRECCION", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tb_resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btn_Ingresar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_consultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btn_Editar1)
                                .addGap(26, 26, 26)
                                .addComponent(btn_eliminar1)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consultar)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ingresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_Editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Editar1ActionPerformed
        // TODO add your handling code here:
       this.getContentPane().setBackground(Color.BLUE);
        if(seleccionEditarValida()){
        String identificacion = this.Tb_resultado.getValueAt(this.Tb_resultado.getSelectedRow(),0).toString();
        FrmEditarCliente frm = new FrmEditarCliente(identificacion,this);
        frm.setVisible(true);
    }
}//GEN-LAST:event_btn_Editar1ActionPerformed

 private boolean seleccionEditarValida(){
    if(Tb_resultado.getSelectedRowCount()!=1){
        JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR SOLO UN REGISTRO", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;  
    }
    return true;
}
private boolean seleccionEliminarValida(){
    if(Tb_resultado.getSelectedRowCount()==0){
        JOptionPane.showMessageDialog(null, "SELECCIONE POR LO MENOS UN REGISTRO", "ERROR", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    String[] opciones = new String[] {"SI", "NO"};
    int opcion = JOptionPane.showOptionDialog(null, "ESTA SEGURO QUE DESEA ELIMINAR LOS REGISTROS SELECCIONADOS???", "SALIR",
        JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, opciones, opciones[1]);
    if(opcion==0){
        return true;
    }else{
        return false;
    }
}   


private boolean registroValido(){

    String tipo = this.cb_tipo.getSelectedItem().toString();
    String descripcion1 = this.txt_descripcion.getText();
                
    if(!tipo.equals("TODOS")){
       if(descripcion1.equals("")){
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR UNA DESCRIPCION", "ERROR", JOptionPane.ERROR_MESSAGE);

       return false;
       }
        
    } return true;

} 
private void actualizar_descripcion(){
    String tipo = this.cb_tipo.getSelectedItem().toString();
    this.txt_descripcion.setText(null);
    if(tipo.equals("TODOS"))
        this.txt_descripcion.setEditable(false);
    else
        this.txt_descripcion.setEditable(true);
}

public void limpiar_Tb_resultado(){
    Tb_resultado.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},new String [] {"IDENTIFICACION", "NOMBRE", "DIRECCION", "TELEFONO"}
            ){boolean[] canEdit = new boolean [] {false, false, false, false};public boolean isCellEditable(int rowIndex, int columnIndex){return canEdit [columnIndex];}});

}

public void consultar_cliente(){
    this.btn_consultarActionPerformed(null);
   
}

private void btn_Ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar2ActionPerformed
    this.getContentPane().setBackground(Color.cyan);
    FrmIngresarCliente frm = new FrmIngresarCliente(this);//rrrrrrrrrr
    frm.setVisible(true);
    
}//GEN-LAST:event_btn_Ingresar2ActionPerformed

private void actualizarTabla(ArrayList registros){
    Object[][] registros2 = new Object[registros.size()][4];
    for(int i=0;i<registros.size();i++){
        Cliente c= (Cliente)registros.get(i);
        registros2[i][0]= c.getIdentificacion();
        registros2[i][1]= c.getNombre();
        registros2[i][2]= c.getDireccion();
        registros2[i][3]= c.getTelefono();    
    }

Tb_resultado.setModel(new javax.swing.table.DefaultTableModel(
            registros2,
            new String [] {
                "IDENTIFICACION", "NOMBRE", "DIRECCION", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

}




private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed
        this.getContentPane().setBackground(Color.DARK_GRAY);
        if(seleccionEliminarValida()){
        String clave = "";
        int [] indices = this.Tb_resultado.getSelectedRows();
            for(int i=0; i< indices.length; i++){
                String clave1 = this.Tb_resultado.getValueAt(indices[i],0).toString();
                clave = clave + "'"+clave1+"',";
                
            }
          System.out.println(clave);
            clave = clave.substring(0,clave.length()-1);
                try{
                    Conexion c = new Conexion();
                    c.conectar();
                    if(c.eliminarCliente(clave)){
                        JOptionPane.showMessageDialog(null, "SE REALIZO LA ELIMINACION CON EXITO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                        this.btn_consultarActionPerformed(null);

                    }else{
                        JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA ELIMINACION", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN LA CONEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
    }
}//GEN-LAST:event_btn_eliminar1ActionPerformed

private void cb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoActionPerformed
        // TODO add your handling code here:
        limpiar_Tb_resultado();
        actualizar_descripcion();
}//GEN-LAST:event_cb_tipoActionPerformed

private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
this.getContentPane().setBackground(Color.BLACK);
       limpiar_Tb_resultado();

   if(registroValido()){
    String descripcion1 = this.txt_descripcion.getText();
    String tipo = this.cb_tipo.getSelectedItem().toString();

    Conexion c = new Conexion();
    try{
        c.conectar();
        ArrayList cliente = c.consultarCliente(descripcion1,tipo);
        actualizarTabla(cliente);
    }catch(Exception e){

    }
   }  
        
}//GEN-LAST:event_btn_consultarActionPerformed
 
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_resultado;
    private javax.swing.JButton btn_Editar1;
    private javax.swing.JButton btn_Ingresar2;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
}
