/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on 24/10/2013, 04:42:42 PM
 */
package formularios;
import entidades.Usuario;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author VR
 */
public class FrmPrincipal extends javax.swing.JFrame {

    
    private Usuario u;

    public FrmPrincipal(Usuario u) {
        this.getContentPane().setBackground(Color.darkGray);
        this.u = u;
        initComponents();
        actualizarMenu();
        
    } 
    public void actualizarMenu(){
    switch(u.getRol()){
            case 'A': //ADMINISTRADOR      
            break;
            case 'O': //OPERADOR    
              this.mi_usuario.setVisible(false);     
            break;    
        } 
    }
   
//     public void setId_Usuario(String id_usuario){
//        
////        this.id_usuario = id_usuario;
//        
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mb_principal = new javax.swing.JMenuBar();
        m_inicio = new javax.swing.JMenu();
        mi_micuenta = new javax.swing.JMenuItem();
        mi_cerrar_sesion = new javax.swing.JMenuItem();
        mi_salir = new javax.swing.JMenuItem();
        m_mantenimiento = new javax.swing.JMenu();
        mi_usuario = new javax.swing.JMenuItem();
        mi_cliente = new javax.swing.JMenuItem();
        mi_telefono = new javax.swing.JMenuItem();
        m_procesos = new javax.swing.JMenu();
        mi_factura = new javax.swing.JMenuItem();
        mi_consultaFactura = new javax.swing.JMenuItem();
        m_ayuda = new javax.swing.JMenu();
        mi_acercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO PRINCIPAL");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo principal2.png"))); // NOI18N

        m_inicio.setText("Inicio");

        mi_micuenta.setText("Mi cuenta");
        m_inicio.add(mi_micuenta);

        mi_cerrar_sesion.setText("Cerrar sesión");
        mi_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cerrar_sesionActionPerformed(evt);
            }
        });
        m_inicio.add(mi_cerrar_sesion);

        mi_salir.setText("Salir");
        mi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_salirActionPerformed(evt);
            }
        });
        m_inicio.add(mi_salir);

        mb_principal.add(m_inicio);

        m_mantenimiento.setText("Mantenimiento");

        mi_usuario.setText("Usuario");
        mi_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_usuarioActionPerformed(evt);
            }
        });
        m_mantenimiento.add(mi_usuario);

        mi_cliente.setText("Cliente");
        mi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_clienteActionPerformed(evt);
            }
        });
        m_mantenimiento.add(mi_cliente);

        mi_telefono.setText("Telefono");
        mi_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_telefonoActionPerformed(evt);
            }
        });
        m_mantenimiento.add(mi_telefono);

        mb_principal.add(m_mantenimiento);

        m_procesos.setText("Procesos");
        m_procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_procesosActionPerformed(evt);
            }
        });

        mi_factura.setText("Ingreso Factura");
        mi_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_facturaActionPerformed(evt);
            }
        });
        m_procesos.add(mi_factura);

        mi_consultaFactura.setText("Consulta Factura");
        mi_consultaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consultaFacturaActionPerformed(evt);
            }
        });
        m_procesos.add(mi_consultaFactura);

        mb_principal.add(m_procesos);

        m_ayuda.setText("Ayuda");

        mi_acercade.setText("Acerca de..");
        mi_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_acercadeActionPerformed(evt);
            }
        });
        m_ayuda.add(mi_acercade);

        mb_principal.add(m_ayuda);

        setJMenuBar(mb_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_telefonoActionPerformed
        // TODO add your handling code here:
        FrmMantenimientoTelefono frm = new FrmMantenimientoTelefono();
        frm.setVisible(true);
        
    }//GEN-LAST:event_mi_telefonoActionPerformed

private void mi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salirActionPerformed
// TODO add your handling code here:
    int eleccion = JOptionPane.showConfirmDialog(null,"REALMENTE DESEA SALIR","CONFIRMAR SALDA",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE) ;
   if (eleccion ==0){
   JOptionPane.showMessageDialog(null, "SALIENDO DEL SISTEMA....");
   System.exit (0);
    }
    
}//GEN-LAST:event_mi_salirActionPerformed

private void mi_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cerrar_sesionActionPerformed
// TODO add your handling code here:
    
    FrmAutenticacionUsuario frm = new FrmAutenticacionUsuario ();
    frm.setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_mi_cerrar_sesionActionPerformed

private void mi_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_usuarioActionPerformed

    FrmMantenimientoUsuario frm = new FrmMantenimientoUsuario ();
    frm.setVisible(true);
   
}//GEN-LAST:event_mi_usuarioActionPerformed

private void mi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_clienteActionPerformed
// TODO add your handling code here:
     FrmMantenimientoCliente frm = new FrmMantenimientoCliente ();
      frm.setVisible(true);  
}//GEN-LAST:event_mi_clienteActionPerformed

private void mi_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_facturaActionPerformed
// TODO add your handling code here:
    FrmFactura frm = new FrmFactura (null,null);
    frm.setVisible(true);
  
}//GEN-LAST:event_mi_facturaActionPerformed

private void m_procesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_procesosActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_m_procesosActionPerformed

private void mi_consultaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consultaFacturaActionPerformed
 
    FrmConsultarFactura frm = new FrmConsultarFactura ();
    frm.setVisible(true);
}//GEN-LAST:event_mi_consultaFacturaActionPerformed

private void mi_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_acercadeActionPerformed
// TODO add your handling code here:
    
    FrmPortada frm = new FrmPortada ();
    frm.setVisible(true);
}//GEN-LAST:event_mi_acercadeActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu m_ayuda;
    private javax.swing.JMenu m_inicio;
    private javax.swing.JMenu m_mantenimiento;
    private javax.swing.JMenu m_procesos;
    private javax.swing.JMenuBar mb_principal;
    private javax.swing.JMenuItem mi_acercade;
    private javax.swing.JMenuItem mi_cerrar_sesion;
    private javax.swing.JMenuItem mi_cliente;
    private javax.swing.JMenuItem mi_consultaFactura;
    private javax.swing.JMenuItem mi_factura;
    private javax.swing.JMenuItem mi_micuenta;
    private javax.swing.JMenuItem mi_salir;
    private javax.swing.JMenuItem mi_telefono;
    private javax.swing.JMenuItem mi_usuario;
    // End of variables declaration//GEN-END:variables
}
